### ISSUE TITLE
Hostname Support

### ISSUE THREAD

**Issue by pcdog** [heximcz/routerboard-backup#1]
I would like to see hostname support, I do not see a technical reason to only support ipv4 Addresses.

I have to rely e.g on /ip cloud dyndns support. I cannot use it this way :(

please change it if you can, should be a simple fix

**Comment by heximcz** [comment]
!! change **addr** type in mysql, addr must be now varchar(255)

> `addr` varchar(255) COLLATE utf8_bin NOT NULL COMMENT 'IP address',

**Comment by pcdog** [comment]
works ;) thanks
