### ISSUE TITLE
Blank password for rbackup user

### ISSUE THREAD

**Issue by alastify** [heximcz/routerboard-backup#12]
Maybe it is worth mentioning that while automatic creation of "rbackup" user account with public key authentication, so someone could assume that this account is protected, however it is not. Created "rbackup" user has blank password so anyone could log in with full privileges to the routerboard without password (eg using winbox).

Or perhaps I am missing something?

**Comment by heximcz** [comment]
The user was assigned a key and it was not possible to connect to it via a password. Now the password is already issued in version >= 7. The latest version therefore adds the possibility of a password. Check the latest version. Changes are in config.yml
