### ISSUE TITLE
Old gitlab repository not recognised

### ISSUE THREAD

**Issue by matijag** [heximcz/routerboard-backup#3]
After upgrade from 0.8 (and fixing the mysql table), rb:backup works, but rb:gitlab returns an error:

```
[2016-03-03 10:26:02] NOTICE: Project 'mikrotik_backup' does not exist in repo. Creating new ...
[Gitlab\Exception\ErrorException]                             
  "name" has already been taken, "path" has already been taken  
 rb:gitlab [-i|--addr ADDR] [--] [<action>]
```

It looks to me like it can not recognise the existing repository, but then can not create a new one because it already exists?

**Comment by heximcz** [comment]
Yes you are right.
What's your version of the gitlab?
Check your installed version: git describe --tags
Do you use any gitlab group?
Can you enable debug in config file and send me output to 'email deleted' ?
