### ISSUE TITLE
.rsc file backup issue

### ISSUE THREAD

**Issue by ZooLMcFLy** [heximcz/routerboard-backup#6]
Dear Heximcz,
I installed and setuped the routerborad-backup same like on the video.
When I teste the backing up, it cannot backup .rsc file.

The mikrotik start create the rsc, but the backup did not wait until it finish.

Where can I give it a delay or a wait time to finish the rsc and after try to download it?

Thanks!
ZooL

**Comment by heximcz** [comment]
Hello,
check your mikrotik routeros version. Same version have a problem with file transfer via SCP (SSH).

**Comment by ZooLMcFLy** [comment]
The routeros is 6.37.4 and 6.38.1.
I think the problem was about the filelisting on the mikrotik. I saw the new files (.backup and .rsc) but the command cannot find that.
I was put 3 lines in the SSHConnector.php after start export and before start download.
That 3 lines:

$this->sshDisconnect($ssh);
sleep(15);
$ssh = $this->sshConnect($addr, $port, true);

After a reconnect it can find the backups. It's a little bit barbarian problem solving, but it is works!

Thank you for your answer, and thanks for that great mikrotik backup solution, I like that!

Best regards!
ZooL

**Comment by heximcz** [comment]
Ok, thank you for test and support. I'll try prepare more robust file transfer.
:+1:

**Comment by heximcz** [comment]
Try please last development (master version) if problem is solved. Thank you.

**Comment by ZooLMcFLy** [comment]
Hi, I changed the SSHconnector.php to the new and checked, but no difference. The problem is same.
After an export command, it looks like wait for the export file, but cannot found it.
The error message was unable to open channel and the .rsc size is zero.
I think is not your script problem, it is a mikrotik bug.

**Comment by heximcz** [comment]
Interestingly, I backs up more than 30 routers across network without problem. OK, I close this issue.
