### ISSUE TITLE
Migration to Gitlab api v4

### ISSUE THREAD

**Issue by jimmyt86** [heximcz/routerboard-backup#8]
Hi,

I just installed and tested tag 0.9.5 against my gitlab-ce omnibus package installation v9.4.0. However I ran into problems caused by Gitlab's deprecation of the v3 API. I was unable to backup to gitlab.  Gitlab's logs showed it was returning 400 errors to some of the api requests. Gitlab will also be fully removing the v3 API on August 22nd.

I've installed an older Gitlab v8.16 server and this works perfectly, this is before the v4 API was introduced.
Documentation from Gitlab about the migration https://docs.gitlab.com/ce/api/v3_to_v4.html

Great software by the way.

Cheers,
James

**Comment by heximcz** [comment]
Hi,
thanks for the info. I look at it asap.

**Comment by heximcz** [comment]
Hi,
please try last commit:
```
git pull
git checkout origin/master
```
**Do not change (url)../v3/ to (url)../v4/ in the config file.**

Work for me with:
```
GitLab 9.4.0
GitLab Shell 5.3.1
GitLab Workhorse v2.3.0
GitLab API v4
```

**Comment by jimmyt86** [comment]
Hi @heximcz.

I've tested against those same gitlab versions but routerboard-backup is still unable to commit into gitlab. I also left the url as v3 as per your instruction.

To be sure I used a clean gitlab install 9.4.2 & a fresh clone of routerboard-backup but had the same issue.

Is there anything else I should try?

Cheers,
James

**Comment by heximcz** [comment]
Hi James,

I work now on script refactoring for [php-gitlab-api](https://github.com/m4tthumphrey/php-gitlab-api/releases), v9.0.0 now support GitLab API V4

**Comment by heximcz** [comment]
Here is still bug for V4. I must wait to close the issue: [#239](https://github.com/m4tthumphrey/php-gitlab-api/issues/239)

**Comment by heximcz** [comment]
Ok. Now is script full compatible with GitLab API V4. Try please last master branch.
